# examples/05_adaptive_wheeler.jl
using QBMM
using StaticArrays
using Printf

println("=== Module 2: Robustness and Error Handling ===")
println("5. Extreme Cases and Adaptive Order Reduction (Adaptive Wheeler)\n")

# Construct a degenerate moment sequence (generated by only 2 discrete nodes)
# Nodes x = [1.0, 2.0], weights w = [0.5, 0.5]
nodes = [1.0, 2.0]
weights = [0.5, 0.5]
m_deg_array = [sum(weights[i] * nodes[i]^k for i in 1:2) for k in 0:7]
m_degenerate = SVector{8,Float64}(m_deg_array...)

println("Degenerate moment sequence (theoretically only supports N=2):")
println(m_degenerate)
println()

println("Attempting Wheeler inversion with N=4 (adaptive framework should safely reduce it to N=2)...")

method_w = Wheeler(4)
res = invert_moments(method_w, m_degenerate)

println("\n--- Results after order reduction ---")
for i in 1:4
    @printf(
        "Node %d: %8.4f, Weight: %8.4f\n",
        i,
        res.nodes[i],
        res.weights[i]
    )
end
println("\nAs can be seen, the extra two node weights were safely set to 0.0 without triggering a division-by-zero crash.")
